/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfase;

/**
 *
 * @author YARITZA
 */
public class Vista_vendedor extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Vista_vendedor.class.getName());

    /**
     * Creates new form Vista_vendedor
     */
    public Vista_vendedor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        pa_ventas = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        pa_nueva_venta = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        imagen_de_vista_vendedor1 = new javax.swing.JLabel();
        imagen_de_vista_vendedor2 = new javax.swing.JLabel();
        pestanas_vista_vendedor = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        tx_nombre_producto = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tx_descripcion_producto = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tx_presio_producto = new javax.swing.JTextField();
        b_new_objeto = new javax.swing.JButton();
        fondo_new__venta = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/inicio_usuario.png"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 60, 70));

        pa_ventas.setBackground(new java.awt.Color(255, 135, 56));
        pa_ventas.setForeground(new java.awt.Color(255, 102, 0));
        pa_ventas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pa_ventasMouseClicked(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Ventas");

        javax.swing.GroupLayout pa_ventasLayout = new javax.swing.GroupLayout(pa_ventas);
        pa_ventas.setLayout(pa_ventasLayout);
        pa_ventasLayout.setHorizontalGroup(
            pa_ventasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pa_ventasLayout.createSequentialGroup()
                .addContainerGap(69, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(66, 66, 66))
        );
        pa_ventasLayout.setVerticalGroup(
            pa_ventasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pa_ventasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        jPanel1.add(pa_ventas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 170, 30));

        pa_nueva_venta.setBackground(new java.awt.Color(255, 135, 56));
        pa_nueva_venta.setForeground(new java.awt.Color(255, 102, 0));
        pa_nueva_venta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pa_nueva_ventaMouseClicked(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nuevo objeto para vender");

        javax.swing.GroupLayout pa_nueva_ventaLayout = new javax.swing.GroupLayout(pa_nueva_venta);
        pa_nueva_venta.setLayout(pa_nueva_ventaLayout);
        pa_nueva_ventaLayout.setHorizontalGroup(
            pa_nueva_ventaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pa_nueva_ventaLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addContainerGap(13, Short.MAX_VALUE))
        );
        pa_nueva_ventaLayout.setVerticalGroup(
            pa_nueva_ventaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pa_nueva_ventaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        jPanel1.add(pa_nueva_venta, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 170, 30));

        imagen_de_vista_vendedor1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icono.png"))); // NOI18N
        imagen_de_vista_vendedor1.setText(" new bienvenido().setVisible(true);");
        jPanel1.add(imagen_de_vista_vendedor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, 500, 90));

        imagen_de_vista_vendedor2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/main-background.jpg"))); // NOI18N
        imagen_de_vista_vendedor2.setText(" new bienvenido().setVisible(true);");
        jPanel1.add(imagen_de_vista_vendedor2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 440));

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        pestanas_vista_vendedor.addTab("tab1", jPanel4);

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        pestanas_vista_vendedor.addTab("tab2", jPanel5);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setText("Dijite el nombre del producto");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, -1));
        jPanel2.add(tx_nombre_producto, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 300, -1));

        jLabel6.setText("Descipcion del objeto");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, -1, -1));
        jPanel2.add(tx_descripcion_producto, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 300, 120));

        jLabel7.setText("Dijite el precio en dolares");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, -1, -1));
        jPanel2.add(tx_presio_producto, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 160, -1));

        b_new_objeto.setText("Subir producto");
        jPanel2.add(b_new_objeto, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, -1, -1));

        fondo_new__venta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo_nuevo_objeto.jpg"))); // NOI18N
        jPanel2.add(fondo_new__venta, new org.netbeans.lib.awtextra.AbsoluteConstraints(-300, 0, 800, 360));

        pestanas_vista_vendedor.addTab("tab3", jPanel2);

        jPanel1.add(pestanas_vista_vendedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 500, 390));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 442, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pa_nueva_ventaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pa_nueva_ventaMouseClicked
       
        pestanas_vista_vendedor.setSelectedIndex(2);
        
    }//GEN-LAST:event_pa_nueva_ventaMouseClicked

    private void pa_ventasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pa_ventasMouseClicked
        pestanas_vista_vendedor.setSelectedIndex(1);
    }//GEN-LAST:event_pa_ventasMouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
    pestanas_vista_vendedor.setSelectedIndex(0);
    }//GEN-LAST:event_jLabel4MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Vista_vendedor().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_new_objeto;
    private javax.swing.JLabel fondo_new__venta;
    private javax.swing.JLabel imagen_de_vista_vendedor1;
    private javax.swing.JLabel imagen_de_vista_vendedor2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel pa_nueva_venta;
    private javax.swing.JPanel pa_ventas;
    private javax.swing.JTabbedPane pestanas_vista_vendedor;
    private javax.swing.JTextField tx_descripcion_producto;
    private javax.swing.JTextField tx_nombre_producto;
    private javax.swing.JTextField tx_presio_producto;
    // End of variables declaration//GEN-END:variables
}
